apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-secret
  namespace: argocd
spec:
  secretName: argocd-tls-secret
  issuerRef:
    name: http-01-staging
    kind: ClusterIssuer
  dnsNames:
  - app.enkidudev.website
  usages:
  - digital signature
  - key encipherment
